2014-02-21 09:41:56,782 - odin_callcenter - callcenter.py - 65 - DEBUG - CallCenter : CallCenter create a new call for uniqueid [1392972116.0] 
2014-02-21 09:41:56,787 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 00 @0FJMTXZ 9002 ]
2014-02-21 09:41:56,795 - odin_callcenter - callcenter.py - 81 - DEBUG - CallCenter : New call created for uniqueid [1392972116.0] extention [4000] caller [9002]
2014-02-21 09:42:02,301 - odin_callcenter - callcenter.py - 182 - DEBUG - CallCenter : CallCenter find callref @0FJMTXZ and send commut to the internal [6005].
2014-02-21 09:42:02,952 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392972116.0] and bridgeduniqueid [1392972122.1] and status [Dial]
2014-02-21 09:42:02,956 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 05 @0FJMTXZ 9002 ]
2014-02-21 09:42:02,962 - odin_callcenter - callcenter.py - 131 - DEBUG - CallCenter : update_call_from_bridge F1Client notified for code [CALLCT] and extention [4000] and callcenter [05]
2014-02-21 09:42:03,015 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 01 @0FJMTXZ 9002 ]
2014-02-21 09:42:03,023 - odin_callcenter - callcenter.py - 98 - DEBUG - CallCenter : update_call_from_channel F1Client for uniqueid [1392972116.0] operator phone ringing 
2014-02-21 09:42:03,827 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392972116.0] and bridgeduniqueid [1392972122.1] and status [Link]
2014-02-21 09:42:03,830 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 02 @0FJMTXZ 9002 ]
2014-02-21 09:42:03,832 - odin_callcenter - callcenter.py - 131 - DEBUG - CallCenter : update_call_from_bridge F1Client notified for code [CALLCT] and extention [4000] and callcenter [02]
2014-02-21 09:44:00,255 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392972116.0] and bridgeduniqueid [1392972122.1] and status [Unlink]
2014-02-21 09:44:01,054 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392972116.0].
2014-02-21 09:44:01,065 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 10 @0FJMTXZ 9002 ]
2014-02-21 09:44:01,072 - odin_callcenter - callcenter.py - 158 - DEBUG - CallCenter : CallCenter the incall removed for uniqueid [1392972116.0].
2014-02-21 10:04:21,393 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973459.2] and bridgeduniqueid [1392973461.3] and status [Dial]
2014-02-21 10:04:21,396 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392973459.2] and bridgeduniqueid [1392973461.3]
2014-02-21 10:04:22,956 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392973459.2].
2014-02-21 10:04:22,957 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392973459.2].
2014-02-21 10:06:10,785 - odin_callcenter - callcenter.py - 65 - DEBUG - CallCenter : CallCenter create a new call for uniqueid [1392973570.4] 
2014-02-21 10:06:10,786 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 00 @4YO7SKZ 9002 ]
2014-02-21 10:06:10,795 - odin_callcenter - callcenter.py - 81 - DEBUG - CallCenter : New call created for uniqueid [1392973570.4] extention [4000] caller [9002]
2014-02-21 10:06:14,868 - odin_callcenter - callcenter.py - 182 - DEBUG - CallCenter : CallCenter find callref @4YO7SKZ and send commut to the internal [6005].
2014-02-21 10:06:15,015 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973570.4] and bridgeduniqueid [1392973574.5] and status [Dial]
2014-02-21 10:06:15,024 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 05 @4YO7SKZ 9002 ]
2014-02-21 10:06:15,028 - odin_callcenter - callcenter.py - 131 - DEBUG - CallCenter : update_call_from_bridge F1Client notified for code [CALLCT] and extention [4000] and callcenter [05]
2014-02-21 10:06:15,053 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 01 @4YO7SKZ 9002 ]
2014-02-21 10:06:15,058 - odin_callcenter - callcenter.py - 98 - DEBUG - CallCenter : update_call_from_channel F1Client for uniqueid [1392973570.4] operator phone ringing 
2014-02-21 10:06:16,479 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973570.4] and bridgeduniqueid [1392973574.5] and status [Link]
2014-02-21 10:06:16,485 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 02 @4YO7SKZ 9002 ]
2014-02-21 10:06:16,495 - odin_callcenter - callcenter.py - 131 - DEBUG - CallCenter : update_call_from_bridge F1Client notified for code [CALLCT] and extention [4000] and callcenter [02]
2014-02-21 10:09:54,046 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973570.4] and bridgeduniqueid [1392973574.5] and status [Unlink]
2014-02-21 10:09:54,087 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392973570.4].
2014-02-21 10:09:54,096 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 10 @4YO7SKZ 9002 ]
2014-02-21 10:09:54,104 - odin_callcenter - callcenter.py - 158 - DEBUG - CallCenter : CallCenter the incall removed for uniqueid [1392973570.4].
2014-02-21 10:11:06,464 - odin_callcenter - callcenter.py - 65 - DEBUG - CallCenter : CallCenter create a new call for uniqueid [1392973866.7] 
2014-02-21 10:11:06,466 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 00 @YV5K2Z2 9002 ]
2014-02-21 10:11:06,484 - odin_callcenter - callcenter.py - 81 - DEBUG - CallCenter : New call created for uniqueid [1392973866.7] extention [4000] caller [9002]
2014-02-21 10:11:15,495 - odin_callcenter - callcenter.py - 182 - DEBUG - CallCenter : CallCenter find callref @YV5K2Z2 and send commut to the internal [6005].
2014-02-21 10:11:15,632 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973866.7] and bridgeduniqueid [1392973875.8] and status [Dial]
2014-02-21 10:11:15,633 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 05 @YV5K2Z2 9002 ]
2014-02-21 10:11:15,636 - odin_callcenter - callcenter.py - 131 - DEBUG - CallCenter : update_call_from_bridge F1Client notified for code [CALLCT] and extention [4000] and callcenter [05]
2014-02-21 10:11:15,655 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 01 @YV5K2Z2 9002 ]
2014-02-21 10:11:15,661 - odin_callcenter - callcenter.py - 98 - DEBUG - CallCenter : update_call_from_channel F1Client for uniqueid [1392973866.7] operator phone ringing 
2014-02-21 10:11:17,341 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973866.7] and bridgeduniqueid [1392973875.8] and status [Link]
2014-02-21 10:11:17,342 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 02 @YV5K2Z2 9002 ]
2014-02-21 10:11:17,344 - odin_callcenter - callcenter.py - 131 - DEBUG - CallCenter : update_call_from_bridge F1Client notified for code [CALLCT] and extention [4000] and callcenter [02]
2014-02-21 10:12:42,151 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11] and status [Dial]
2014-02-21 10:12:42,155 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11]
2014-02-21 10:12:47,198 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973866.7] and bridgeduniqueid [1392973875.8] and status [Unlink]
2014-02-21 10:12:47,227 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392973866.7].
2014-02-21 10:12:47,230 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 10 @YV5K2Z2 9002 ]
2014-02-21 10:12:47,236 - odin_callcenter - callcenter.py - 158 - DEBUG - CallCenter : CallCenter the incall removed for uniqueid [1392973866.7].
2014-02-21 10:12:55,519 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11] and status [Link]
2014-02-21 10:12:55,520 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11]
2014-02-21 10:12:56,093 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11] and status [Link]
2014-02-21 10:12:56,102 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11]
2014-02-21 10:12:56,173 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11] and status [Link]
2014-02-21 10:12:56,176 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11]
2014-02-21 10:12:56,223 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11] and status [Unlink]
2014-02-21 10:12:56,228 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392973961.10] and bridgeduniqueid [1392973962.11]
2014-02-21 10:12:56,245 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392973961.10].
2014-02-21 10:12:56,249 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392973961.10].
2014-02-21 10:13:02,756 - odin_callcenter - callcenter.py - 65 - DEBUG - CallCenter : CallCenter create a new call for uniqueid [1392973982.12] 
2014-02-21 10:13:02,757 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 00 @JKZLOSW 9002 ]
2014-02-21 10:13:02,763 - odin_callcenter - callcenter.py - 81 - DEBUG - CallCenter : New call created for uniqueid [1392973982.12] extention [4000] caller [9002]
2014-02-21 10:13:22,358 - odin_callcenter - callcenter.py - 182 - DEBUG - CallCenter : CallCenter find callref @JKZLOSW and send commut to the internal [6005].
2014-02-21 10:13:22,500 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973982.12] and bridgeduniqueid [1392974002.13] and status [Dial]
2014-02-21 10:13:22,501 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 05 @JKZLOSW 9002 ]
2014-02-21 10:13:22,504 - odin_callcenter - callcenter.py - 131 - DEBUG - CallCenter : update_call_from_bridge F1Client notified for code [CALLCT] and extention [4000] and callcenter [05]
2014-02-21 10:13:22,523 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 01 @JKZLOSW 9002 ]
2014-02-21 10:13:22,528 - odin_callcenter - callcenter.py - 98 - DEBUG - CallCenter : update_call_from_channel F1Client for uniqueid [1392973982.12] operator phone ringing 
2014-02-21 10:13:24,894 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973982.12] and bridgeduniqueid [1392974002.13] and status [Link]
2014-02-21 10:13:24,900 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 02 @JKZLOSW 9002 ]
2014-02-21 10:13:24,904 - odin_callcenter - callcenter.py - 131 - DEBUG - CallCenter : update_call_from_bridge F1Client notified for code [CALLCT] and extention [4000] and callcenter [02]
2014-02-21 10:13:32,091 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16] and status [Dial]
2014-02-21 10:13:32,097 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16]
2014-02-21 10:13:34,446 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16] and status [Link]
2014-02-21 10:13:34,449 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16]
2014-02-21 10:13:34,782 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16] and status [Link]
2014-02-21 10:13:34,788 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16]
2014-02-21 10:13:34,855 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16] and status [Link]
2014-02-21 10:13:34,858 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16]
2014-02-21 10:13:34,905 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16] and status [Unlink]
2014-02-21 10:13:34,906 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974011.15] and bridgeduniqueid [1392974011.16]
2014-02-21 10:13:34,932 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974011.15].
2014-02-21 10:13:34,937 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974011.15].
2014-02-21 10:13:57,492 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19] and status [Dial]
2014-02-21 10:13:57,494 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19]
2014-02-21 10:13:59,369 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19] and status [Link]
2014-02-21 10:13:59,372 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19]
2014-02-21 10:13:59,634 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19] and status [Link]
2014-02-21 10:13:59,635 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19]
2014-02-21 10:13:59,700 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19] and status [Link]
2014-02-21 10:13:59,703 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19]
2014-02-21 10:13:59,741 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19] and status [Unlink]
2014-02-21 10:13:59,743 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974037.18] and bridgeduniqueid [1392974037.19]
2014-02-21 10:13:59,762 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974037.18].
2014-02-21 10:13:59,764 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974037.18].
2014-02-21 10:14:24,216 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392973982.12] and bridgeduniqueid [1392974002.13] and status [Unlink]
2014-02-21 10:14:24,243 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392973982.12].
2014-02-21 10:14:24,245 - odin_callcenter - callcenter.py - 47 - DEBUG - CallCenter : __send_callcenter_message [ 4000 10 @JKZLOSW 9002 ]
2014-02-21 10:14:24,249 - odin_callcenter - callcenter.py - 158 - DEBUG - CallCenter : CallCenter the incall removed for uniqueid [1392973982.12].
2014-02-21 10:15:02,542 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22] and status [Dial]
2014-02-21 10:15:02,544 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22]
2014-02-21 10:15:04,858 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22] and status [Link]
2014-02-21 10:15:04,860 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22]
2014-02-21 10:15:05,142 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22] and status [Link]
2014-02-21 10:15:05,153 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22]
2014-02-21 10:15:05,269 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22] and status [Link]
2014-02-21 10:15:05,272 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22]
2014-02-21 10:15:05,357 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22] and status [Unlink]
2014-02-21 10:15:05,358 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974102.21] and bridgeduniqueid [1392974102.22]
2014-02-21 10:15:05,393 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974102.21].
2014-02-21 10:15:05,394 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974102.21].
2014-02-21 10:15:29,597 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24] and status [Dial]
2014-02-21 10:15:29,600 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24]
2014-02-21 10:15:31,875 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24] and status [Link]
2014-02-21 10:15:31,878 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24]
2014-02-21 10:15:51,980 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27] and status [Dial]
2014-02-21 10:15:51,983 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27]
2014-02-21 10:15:54,100 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27] and status [Link]
2014-02-21 10:15:54,101 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27]
2014-02-21 10:15:54,351 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27] and status [Link]
2014-02-21 10:15:54,355 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27]
2014-02-21 10:15:54,427 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27] and status [Link]
2014-02-21 10:15:54,431 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27]
2014-02-21 10:15:54,472 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27] and status [Unlink]
2014-02-21 10:15:54,473 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974151.26] and bridgeduniqueid [1392974151.27]
2014-02-21 10:15:54,494 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974151.26].
2014-02-21 10:15:54,496 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974151.26].
2014-02-21 10:16:11,328 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30] and status [Dial]
2014-02-21 10:16:11,332 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30]
2014-02-21 10:16:12,840 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24] and status [Unlink]
2014-02-21 10:16:12,841 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24]
2014-02-21 10:16:12,904 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24] and status [Link]
2014-02-21 10:16:12,905 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24]
2014-02-21 10:16:12,957 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30] and status [Link]
2014-02-21 10:16:12,961 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30]
2014-02-21 10:16:13,181 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30] and status [Link]
2014-02-21 10:16:13,185 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30]
2014-02-21 10:16:13,252 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30] and status [Link]
2014-02-21 10:16:13,255 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30]
2014-02-21 10:16:13,294 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30] and status [Unlink]
2014-02-21 10:16:13,295 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974170.29] and bridgeduniqueid [1392974171.30]
2014-02-21 10:16:13,321 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974170.29].
2014-02-21 10:16:13,322 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974170.29].
2014-02-21 10:16:31,951 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24] and status [Unlink]
2014-02-21 10:16:31,952 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24]
2014-02-21 10:16:31,975 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24] and status [Link]
2014-02-21 10:16:31,976 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24]
2014-02-21 10:16:36,073 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24] and status [Unlink]
2014-02-21 10:16:36,080 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974129.23] and bridgeduniqueid [1392974129.24]
2014-02-21 10:16:36,106 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974129.23].
2014-02-21 10:16:36,114 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974129.23].
2014-02-21 10:19:37,968 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974375.31] and bridgeduniqueid [1392974377.32] and status [Dial]
2014-02-21 10:19:37,970 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974375.31] and bridgeduniqueid [1392974377.32]
2014-02-21 10:19:40,859 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974375.31] and bridgeduniqueid [1392974377.32] and status [Link]
2014-02-21 10:19:40,867 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974375.31] and bridgeduniqueid [1392974377.32]
2014-02-21 10:19:41,347 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974375.31] and bridgeduniqueid [1392974377.32] and status [Unlink]
2014-02-21 10:19:41,355 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974375.31] and bridgeduniqueid [1392974377.32]
2014-02-21 10:19:41,386 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974375.31].
2014-02-21 10:19:41,395 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974375.31].
2014-02-21 10:20:44,068 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34] and status [Dial]
2014-02-21 10:20:44,073 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34]
2014-02-21 10:20:46,876 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34] and status [Link]
2014-02-21 10:20:46,885 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34]
2014-02-21 10:23:12,665 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37] and status [Dial]
2014-02-21 10:23:12,667 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37]
2014-02-21 10:23:15,827 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34] and status [Unlink]
2014-02-21 10:23:15,831 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34]
2014-02-21 10:23:15,885 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34] and status [Link]
2014-02-21 10:23:15,896 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34]
2014-02-21 10:23:15,942 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37] and status [Link]
2014-02-21 10:23:15,956 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37]
2014-02-21 10:23:16,160 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37] and status [Link]
2014-02-21 10:23:16,162 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37]
2014-02-21 10:23:16,231 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37] and status [Link]
2014-02-21 10:23:16,236 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37]
2014-02-21 10:23:16,274 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37] and status [Unlink]
2014-02-21 10:23:16,276 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974592.36] and bridgeduniqueid [1392974592.37]
2014-02-21 10:23:16,294 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974592.36].
2014-02-21 10:23:16,298 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974592.36].
2014-02-21 10:23:27,774 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34] and status [Unlink]
2014-02-21 10:23:27,776 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34]
2014-02-21 10:23:27,802 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34] and status [Link]
2014-02-21 10:23:27,805 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34]
2014-02-21 10:26:14,356 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34] and status [Unlink]
2014-02-21 10:26:14,357 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392974443.33] and bridgeduniqueid [1392974443.34]
2014-02-21 10:26:14,397 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392974443.33].
2014-02-21 10:26:14,402 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392974443.33].
2014-02-21 10:46:47,996 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976007.38] and bridgeduniqueid [1392976007.39] and status [Dial]
2014-02-21 10:46:48,036 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976007.38] and bridgeduniqueid [1392976007.39]
2014-02-21 10:46:50,520 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976007.38] and bridgeduniqueid [1392976007.39] and status [Link]
2014-02-21 10:46:50,523 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976007.38] and bridgeduniqueid [1392976007.39]
2014-02-21 10:47:21,809 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976007.38] and bridgeduniqueid [1392976007.39] and status [Unlink]
2014-02-21 10:47:21,810 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976007.38] and bridgeduniqueid [1392976007.39]
2014-02-21 10:47:21,915 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392976007.38].
2014-02-21 10:47:21,916 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392976007.38].
2014-02-21 10:58:05,563 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976685.41] and bridgeduniqueid [1392976685.42] and status [Dial]
2014-02-21 10:58:05,564 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976685.41] and bridgeduniqueid [1392976685.42]
2014-02-21 10:58:12,254 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976685.41] and bridgeduniqueid [1392976685.42] and status [Link]
2014-02-21 10:58:12,255 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976685.41] and bridgeduniqueid [1392976685.42]
2014-02-21 10:58:14,388 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976685.41] and bridgeduniqueid [1392976685.42] and status [Unlink]
2014-02-21 10:58:14,399 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976685.41] and bridgeduniqueid [1392976685.42]
2014-02-21 10:58:14,434 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392976685.41].
2014-02-21 10:58:14,443 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392976685.41].
2014-02-21 10:59:50,213 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976790.43] and bridgeduniqueid [1392976790.44] and status [Dial]
2014-02-21 10:59:50,215 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976790.43] and bridgeduniqueid [1392976790.44]
2014-02-21 10:59:52,641 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976790.43] and bridgeduniqueid [1392976790.44] and status [Link]
2014-02-21 10:59:52,642 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976790.43] and bridgeduniqueid [1392976790.44]
2014-02-21 10:59:52,966 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976790.43] and bridgeduniqueid [1392976790.44] and status [Unlink]
2014-02-21 10:59:52,969 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976790.43] and bridgeduniqueid [1392976790.44]
2014-02-21 10:59:53,026 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392976790.43].
2014-02-21 10:59:53,036 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392976790.43].
2014-02-21 11:00:10,386 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976810.45] and bridgeduniqueid [1392976810.46] and status [Dial]
2014-02-21 11:00:10,388 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976810.45] and bridgeduniqueid [1392976810.46]
2014-02-21 11:00:13,593 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976810.45] and bridgeduniqueid [1392976810.46] and status [Link]
2014-02-21 11:00:13,596 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976810.45] and bridgeduniqueid [1392976810.46]
2014-02-21 11:00:14,418 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392976810.45] and bridgeduniqueid [1392976810.46] and status [Unlink]
2014-02-21 11:00:14,419 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392976810.45] and bridgeduniqueid [1392976810.46]
2014-02-21 11:00:14,470 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392976810.45].
2014-02-21 11:00:14,479 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392976810.45].
2014-02-21 11:22:06,397 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392978126.47] and bridgeduniqueid [1392978126.48] and status [Dial]
2014-02-21 11:22:06,399 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392978126.47] and bridgeduniqueid [1392978126.48]
2014-02-21 11:22:09,620 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392978126.47] and bridgeduniqueid [1392978126.48] and status [Link]
2014-02-21 11:22:09,628 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392978126.47] and bridgeduniqueid [1392978126.48]
2014-02-21 11:26:32,717 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392978126.47] and bridgeduniqueid [1392978126.48] and status [Unlink]
2014-02-21 11:26:32,719 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392978126.47] and bridgeduniqueid [1392978126.48]
2014-02-21 11:26:32,801 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392978126.47].
2014-02-21 11:26:32,806 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392978126.47].
2014-02-21 11:27:49,954 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392978469.49] and bridgeduniqueid [1392978469.50] and status [Dial]
2014-02-21 11:27:49,956 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392978469.49] and bridgeduniqueid [1392978469.50]
2014-02-21 11:27:52,569 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392978469.49] and bridgeduniqueid [1392978469.50] and status [Link]
2014-02-21 11:27:52,570 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392978469.49] and bridgeduniqueid [1392978469.50]
2014-02-21 11:28:08,868 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392978469.49] and bridgeduniqueid [1392978469.50] and status [Unlink]
2014-02-21 11:28:08,876 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392978469.49] and bridgeduniqueid [1392978469.50]
2014-02-21 11:28:08,921 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392978469.49].
2014-02-21 11:28:08,922 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392978469.49].
2014-02-21 11:43:13,369 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392979393.51] and bridgeduniqueid [1392979393.52] and status [Dial]
2014-02-21 11:43:13,373 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392979393.51] and bridgeduniqueid [1392979393.52]
2014-02-21 11:43:15,461 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392979393.51] and bridgeduniqueid [1392979393.52] and status [Link]
2014-02-21 11:43:15,463 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392979393.51] and bridgeduniqueid [1392979393.52]
2014-02-21 11:44:17,795 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392979393.51] and bridgeduniqueid [1392979393.52] and status [Unlink]
2014-02-21 11:44:17,803 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392979393.51] and bridgeduniqueid [1392979393.52]
2014-02-21 11:44:17,833 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392979393.51].
2014-02-21 11:44:17,834 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392979393.51].
2014-02-21 11:47:11,657 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392979631.53] and bridgeduniqueid [1392979631.54] and status [Dial]
2014-02-21 11:47:11,658 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392979631.53] and bridgeduniqueid [1392979631.54]
2014-02-21 11:47:13,637 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392979631.53] and bridgeduniqueid [1392979631.54] and status [Link]
2014-02-21 11:47:13,638 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392979631.53] and bridgeduniqueid [1392979631.54]
2014-02-21 11:58:06,004 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392979631.53] and bridgeduniqueid [1392979631.54] and status [Unlink]
2014-02-21 11:58:06,006 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392979631.53] and bridgeduniqueid [1392979631.54]
2014-02-21 11:58:06,050 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392979631.53].
2014-02-21 11:58:06,054 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392979631.53].
2014-02-21 14:32:34,419 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392989554.55] and bridgeduniqueid [1392989554.56] and status [Dial]
2014-02-21 14:32:34,444 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392989554.55] and bridgeduniqueid [1392989554.56]
2014-02-21 14:32:36,277 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392989554.55] and bridgeduniqueid [1392989554.56] and status [Link]
2014-02-21 14:32:36,278 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392989554.55] and bridgeduniqueid [1392989554.56]
2014-02-21 14:35:32,412 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392989554.55] and bridgeduniqueid [1392989554.56] and status [Unlink]
2014-02-21 14:35:32,413 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392989554.55] and bridgeduniqueid [1392989554.56]
2014-02-21 14:35:32,557 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392989554.55].
2014-02-21 14:35:32,559 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392989554.55].
2014-02-21 14:40:09,298 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392990009.57] and bridgeduniqueid [1392990009.58] and status [Dial]
2014-02-21 14:40:09,300 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392990009.57] and bridgeduniqueid [1392990009.58]
2014-02-21 14:40:11,029 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392990009.57] and bridgeduniqueid [1392990009.58] and status [Link]
2014-02-21 14:40:11,031 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392990009.57] and bridgeduniqueid [1392990009.58]
2014-02-21 14:41:09,694 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392990009.57] and bridgeduniqueid [1392990009.58] and status [Unlink]
2014-02-21 14:41:09,695 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392990009.57] and bridgeduniqueid [1392990009.58]
2014-02-21 14:41:09,808 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392990009.57].
2014-02-21 14:41:09,809 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392990009.57].
2014-02-21 15:23:00,418 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392992580.60] and bridgeduniqueid [1392992580.61] and status [Dial]
2014-02-21 15:23:00,419 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392992580.60] and bridgeduniqueid [1392992580.61]
2014-02-21 15:23:02,007 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392992580.60] and bridgeduniqueid [1392992580.61] and status [Link]
2014-02-21 15:23:02,008 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392992580.60] and bridgeduniqueid [1392992580.61]
2014-02-21 15:23:28,290 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392992580.60] and bridgeduniqueid [1392992580.61] and status [Unlink]
2014-02-21 15:23:28,291 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392992580.60] and bridgeduniqueid [1392992580.61]
2014-02-21 15:23:28,350 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392992580.60].
2014-02-21 15:23:28,360 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392992580.60].
2014-02-21 15:42:37,406 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392993757.62] and bridgeduniqueid [1392993757.63] and status [Dial]
2014-02-21 15:42:37,407 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392993757.62] and bridgeduniqueid [1392993757.63]
2014-02-21 15:42:41,635 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392993757.62] and bridgeduniqueid [1392993757.63] and status [Link]
2014-02-21 15:42:41,638 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392993757.62] and bridgeduniqueid [1392993757.63]
2014-02-21 15:43:01,710 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392993757.62] and bridgeduniqueid [1392993757.63] and status [Unlink]
2014-02-21 15:43:01,711 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392993757.62] and bridgeduniqueid [1392993757.63]
2014-02-21 15:43:01,783 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392993757.62].
2014-02-21 15:43:01,790 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392993757.62].
2014-02-21 15:47:42,549 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994062.64] and bridgeduniqueid [1392994062.65] and status [Dial]
2014-02-21 15:47:42,550 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994062.64] and bridgeduniqueid [1392994062.65]
2014-02-21 15:47:45,100 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994062.64] and bridgeduniqueid [1392994062.65] and status [Link]
2014-02-21 15:47:45,105 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994062.64] and bridgeduniqueid [1392994062.65]
2014-02-21 15:49:54,199 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994062.64] and bridgeduniqueid [1392994062.65] and status [Unlink]
2014-02-21 15:49:54,209 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994062.64] and bridgeduniqueid [1392994062.65]
2014-02-21 15:49:54,275 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392994062.64].
2014-02-21 15:49:54,287 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392994062.64].
2014-02-21 15:51:15,843 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994275.66] and bridgeduniqueid [1392994275.67] and status [Dial]
2014-02-21 15:51:15,850 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994275.66] and bridgeduniqueid [1392994275.67]
2014-02-21 15:51:17,591 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994275.66] and bridgeduniqueid [1392994275.67] and status [Link]
2014-02-21 15:51:17,596 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994275.66] and bridgeduniqueid [1392994275.67]
2014-02-21 15:52:51,736 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994275.66] and bridgeduniqueid [1392994275.67] and status [Unlink]
2014-02-21 15:52:51,738 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994275.66] and bridgeduniqueid [1392994275.67]
2014-02-21 15:52:51,854 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392994275.66].
2014-02-21 15:52:51,864 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392994275.66].
2014-02-21 15:54:29,987 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994469.68] and bridgeduniqueid [1392994469.69] and status [Dial]
2014-02-21 15:54:29,991 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994469.68] and bridgeduniqueid [1392994469.69]
2014-02-21 15:54:31,592 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994469.68] and bridgeduniqueid [1392994469.69] and status [Link]
2014-02-21 15:54:31,593 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994469.68] and bridgeduniqueid [1392994469.69]
2014-02-21 15:57:10,292 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392994469.68] and bridgeduniqueid [1392994469.69] and status [Unlink]
2014-02-21 15:57:10,293 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392994469.68] and bridgeduniqueid [1392994469.69]
2014-02-21 15:57:10,358 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392994469.68].
2014-02-21 15:57:10,373 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392994469.68].
2014-02-21 16:06:09,526 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995169.70] and bridgeduniqueid [1392995169.71] and status [Dial]
2014-02-21 16:06:09,529 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995169.70] and bridgeduniqueid [1392995169.71]
2014-02-21 16:06:10,787 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995169.70] and bridgeduniqueid [1392995169.71] and status [Link]
2014-02-21 16:06:10,795 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995169.70] and bridgeduniqueid [1392995169.71]
2014-02-21 16:09:06,909 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995169.70] and bridgeduniqueid [1392995169.71] and status [Unlink]
2014-02-21 16:09:06,910 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995169.70] and bridgeduniqueid [1392995169.71]
2014-02-21 16:09:06,962 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392995169.70].
2014-02-21 16:09:06,963 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392995169.70].
2014-02-21 16:09:10,199 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995350.72] and bridgeduniqueid [1392995350.73] and status [Dial]
2014-02-21 16:09:10,202 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995350.72] and bridgeduniqueid [1392995350.73]
2014-02-21 16:09:14,282 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995350.72] and bridgeduniqueid [1392995350.73] and status [Link]
2014-02-21 16:09:14,284 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995350.72] and bridgeduniqueid [1392995350.73]
2014-02-21 16:09:44,150 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995350.72] and bridgeduniqueid [1392995350.73] and status [Unlink]
2014-02-21 16:09:44,161 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995350.72] and bridgeduniqueid [1392995350.73]
2014-02-21 16:09:44,219 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392995350.72].
2014-02-21 16:09:44,228 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392995350.72].
2014-02-21 16:11:50,711 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995510.74] and bridgeduniqueid [1392995510.75] and status [Dial]
2014-02-21 16:11:50,712 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995510.74] and bridgeduniqueid [1392995510.75]
2014-02-21 16:11:55,069 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995510.74] and bridgeduniqueid [1392995510.75] and status [Link]
2014-02-21 16:11:55,077 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995510.74] and bridgeduniqueid [1392995510.75]
2014-02-21 16:15:58,334 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78] and status [Dial]
2014-02-21 16:15:58,334 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78]
2014-02-21 16:16:01,069 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78] and status [Link]
2014-02-21 16:16:01,072 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78]
2014-02-21 16:16:01,284 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78] and status [Link]
2014-02-21 16:16:01,295 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78]
2014-02-21 16:16:01,411 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78] and status [Link]
2014-02-21 16:16:01,412 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78]
2014-02-21 16:16:01,453 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78] and status [Unlink]
2014-02-21 16:16:01,454 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995758.77] and bridgeduniqueid [1392995758.78]
2014-02-21 16:16:01,482 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392995758.77].
2014-02-21 16:16:01,483 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392995758.77].
2014-02-21 16:16:26,994 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995510.74] and bridgeduniqueid [1392995510.75] and status [Unlink]
2014-02-21 16:16:27,005 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995510.74] and bridgeduniqueid [1392995510.75]
2014-02-21 16:16:27,063 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392995510.74].
2014-02-21 16:16:27,067 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392995510.74].
2014-02-21 16:17:45,808 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995865.79] and bridgeduniqueid [1392995865.80] and status [Dial]
2014-02-21 16:17:45,814 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995865.79] and bridgeduniqueid [1392995865.80]
2014-02-21 16:17:48,592 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995865.79] and bridgeduniqueid [1392995865.80] and status [Link]
2014-02-21 16:17:48,594 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995865.79] and bridgeduniqueid [1392995865.80]
2014-02-21 16:18:17,923 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995865.79] and bridgeduniqueid [1392995865.80] and status [Unlink]
2014-02-21 16:18:17,940 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995865.79] and bridgeduniqueid [1392995865.80]
2014-02-21 16:18:17,970 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392995865.79].
2014-02-21 16:18:17,972 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392995865.79].
2014-02-21 16:18:26,408 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995906.82] and bridgeduniqueid [1392995906.83] and status [Dial]
2014-02-21 16:18:26,409 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995906.82] and bridgeduniqueid [1392995906.83]
2014-02-21 16:18:30,806 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995906.82] and bridgeduniqueid [1392995906.83] and status [Link]
2014-02-21 16:18:30,807 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995906.82] and bridgeduniqueid [1392995906.83]
2014-02-21 16:18:33,642 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392995906.82] and bridgeduniqueid [1392995906.83] and status [Unlink]
2014-02-21 16:18:33,643 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392995906.82] and bridgeduniqueid [1392995906.83]
2014-02-21 16:18:33,668 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392995906.82].
2014-02-21 16:18:33,673 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392995906.82].
2014-02-21 16:31:34,846 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392996694.84] and bridgeduniqueid [1392996694.85] and status [Dial]
2014-02-21 16:31:34,850 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392996694.84] and bridgeduniqueid [1392996694.85]
2014-02-21 16:31:36,024 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392996694.84] and bridgeduniqueid [1392996694.85] and status [Link]
2014-02-21 16:31:36,025 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392996694.84] and bridgeduniqueid [1392996694.85]
2014-02-21 16:31:59,884 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392996694.84] and bridgeduniqueid [1392996694.85] and status [Unlink]
2014-02-21 16:31:59,893 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392996694.84] and bridgeduniqueid [1392996694.85]
2014-02-21 16:31:59,947 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392996694.84].
2014-02-21 16:31:59,954 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392996694.84].
2014-02-21 16:44:40,986 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392997480.86] and bridgeduniqueid [1392997480.87] and status [Dial]
2014-02-21 16:44:40,991 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392997480.86] and bridgeduniqueid [1392997480.87]
2014-02-21 16:44:43,937 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392997480.86] and bridgeduniqueid [1392997480.87] and status [Link]
2014-02-21 16:44:43,940 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392997480.86] and bridgeduniqueid [1392997480.87]
2014-02-21 16:44:50,709 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392997480.86] and bridgeduniqueid [1392997480.87] and status [Unlink]
2014-02-21 16:44:50,720 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392997480.86] and bridgeduniqueid [1392997480.87]
2014-02-21 16:44:50,890 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392997480.86].
2014-02-21 16:44:50,895 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392997480.86].
2014-02-21 16:45:46,603 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392997546.88] and bridgeduniqueid [1392997546.89] and status [Dial]
2014-02-21 16:45:46,604 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392997546.88] and bridgeduniqueid [1392997546.89]
2014-02-21 16:45:48,963 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392997546.88] and bridgeduniqueid [1392997546.89] and status [Link]
2014-02-21 16:45:48,968 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392997546.88] and bridgeduniqueid [1392997546.89]
2014-02-21 16:46:10,955 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392997546.88] and bridgeduniqueid [1392997546.89] and status [Unlink]
2014-02-21 16:46:10,984 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392997546.88] and bridgeduniqueid [1392997546.89]
2014-02-21 16:46:11,068 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392997546.88].
2014-02-21 16:46:11,078 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392997546.88].
2014-02-21 17:07:34,999 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392998854.91] and bridgeduniqueid [1392998854.92] and status [Dial]
2014-02-21 17:07:35,000 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392998854.91] and bridgeduniqueid [1392998854.92]
2014-02-21 17:07:54,293 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392998854.91] and bridgeduniqueid [1392998854.92] and status [Link]
2014-02-21 17:07:54,295 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392998854.91] and bridgeduniqueid [1392998854.92]
2014-02-21 17:10:06,996 - odin_callcenter - callcenter.py - 107 - DEBUG - CallCenter : update_call_from_bridge for uniqueid [1392998854.91] and bridgeduniqueid [1392998854.92] and status [Unlink]
2014-02-21 17:10:06,998 - odin_callcenter - callcenter.py - 136 - DEBUG - CallCenter : Can't update_call_from_bridge for uniqueid [1392998854.91] and bridgeduniqueid [1392998854.92]
2014-02-21 17:10:07,100 - odin_callcenter - callcenter.py - 143 - DEBUG - CallCenter : Removing an incall for [1392998854.91].
2014-02-21 17:10:07,104 - odin_callcenter - callcenter.py - 160 - INFO - CallCenter : CallCenter can't find incall for uniqueid [1392998854.91].
